use SistemaSolicitudes

CREATE TABLE MT_EXPEDIENTE_RECURSO (
    ID_EXPEDIENTE INT IDENTITY(1,1) PRIMARY KEY,
    FECHA_NOTIFICACION_ADMISION DATE NULL,
    RESPUESTA_SOLICITUD NVARCHAR(MAX) NULL,
    FECHA_ACUERDO DATE NULL,
    CONTENIDO_ACUERDO NVARCHAR(MAX) NULL,
    MATERIA_RECURSO NVARCHAR(200) NULL,
    RAZON_INTERPOSICION NVARCHAR(MAX) NULL,
    SENTIDO_RESOLUCION NVARCHAR(200) NULL,
    FECHA_NOTIFICACION DATE NULL,
    FOLIO_SOLICITUD NVARCHAR(100) NULL,
    FECHA_CONTESTACION_RECURSO DATE NULL,
    CONTENIDO_ACUERDO_FINAL NVARCHAR(MAX) NULL,
    FECHA_REGISTRO DATETIME NOT NULL DEFAULT(GETDATE())
);