use SistemaSolicitudes


CREATE TABLE MT_EXPEDIENTE_ARCHIVOS (
    ID_ARCHIVO INT IDENTITY(1,1) PRIMARY KEY,
    ID_EXPEDIENTE INT NOT NULL,
    NOMBRE_ARCHIVO NVARCHAR(255) NOT NULL,
    PDF_DATA VARBINARY(MAX) NOT NULL,
    FECHA_REGISTRO DATETIME NOT NULL DEFAULT(GETDATE())
);

ALTER TABLE MT_EXPEDIENTE_ARCHIVOS
ADD CONSTRAINT FK_ARCHIVOS_EXPEDIENTE
FOREIGN KEY (ID_EXPEDIENTE)
REFERENCES MT_EXPEDIENTE_RECURSO(ID_EXPEDIENTE);


UPDATE MT_EXPEDIENTE_RECURSO
SET FECHA_REGISTRO = GETDATE()
WHERE FECHA_REGISTRO IS NULL;

select * from MT_EXPEDIENTE_ARCHIVOS
