use SistemaSolicitudes
drop table MT_RECURSO_REVISION

GO

CREATE TABLE MT_RECURSO_REVISION (
    ID_RECURSO INT IDENTITY(1,1) PRIMARY KEY,
    NUMERO_RECURSO NVARCHAR(50) NOT NULL,
    ESTATUS NVARCHAR(100) NOT NULL,
    CONTENIDO_SOLICITUD NVARCHAR(MAX) NOT NULL,
    NOMBRE_RECURRENTE NVARCHAR(200) NOT NULL,
    SENTIDO_CONTESTACION NVARCHAR(200) NOT NULL,
    FECHA_ACUERDO DATE NOT NULL,
    FECHA_REGISTRO DATETIME NOT NULL DEFAULT(GETDATE())
);
GO
