// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolicitudesAPI.Models;

#nullable disable

namespace SolicitudesAPI.Migrations
{
    [DbContext(typeof(SistemaSolicitudesContext))]
    partial class SistemaSolicitudesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SolicitudesAPI.Models.AcuerdoSeguimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContenidoAcuerdo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DenunciaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAcuerdo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DenunciaId");

                    b.ToTable("AcuerdosSeguimiento");
                });

            modelBuilder.Entity("SolicitudesAPI.Models.Calendario", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Calendario", (string)null);
                });

            modelBuilder.Entity("SolicitudesAPI.Models.Denuncia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EstatusActual")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaAdmision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCierreInstruccion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInformeJustificado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime2");

                    b.Property<string>("FraccionArticulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroExpediente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RazonInterposicion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SentidoInforme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SentidoResolucion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UltimaFechaEstado")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Denuncias");
                });

            modelBuilder.Entity("SolicitudesAPI.Models.DiaInhabilManual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DiaInhabilManual");
                });

            modelBuilder.Entity("SolicitudesAPI.Models.Expediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ampliacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AreaPoseedoraInformacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CiudadSolicitante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cobro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComoDeseaRecibirRespuestaPersonaSolicitante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContenidoSolicitud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronicoSolicitante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatosRecursoRevision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaLimitePrevencion10dias")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaLimiteRespuesta10dias")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaLimiteRespuesta20dias")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRespuesta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaSesionComiteAmpliacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Folio")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Materia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedioRecepcionSolicitudManual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MesAdmision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModalidadEntrega")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreSolicitante")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroRecursoRevision")
                        .HasColumnType("int");

                    b.Property<int>("NumeroSesionComiteAmpliacion")
                        .HasColumnType("int");

                    b.Property<string>("PrecisionSentidoRespuesta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Prevencion")
                        .HasColumnType("bit");

                    b.Property<int>("PromedioDiasRespuesta")
                        .HasColumnType("int");

                    b.Property<string>("RecibidaRegistrada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecursoRevision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SentidoRespuesta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubsanaPrevencionReinicoTramite")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SubsanaPrevencion_ReinicoTramite");

                    b.Property<string>("Tematica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TematicaEspecifica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDerecho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoSolicitud")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Solicitu__3214EC27AA69A3A2");

                    b.ToTable("Expedientes");
                });

            modelBuilder.Entity("SolicitudesAPI.Models.ExpedienteDigital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DenunciaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreDocumento")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DenunciaId");

                    b.ToTable("ExpedientesDigitales");
                });

            modelBuilder.Entity("SolicitudesAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4000)")
                        .HasColumnName("password");

                    b.HasKey("Id")
                        .HasName("PK__Usuarios__3214EC27AA69A3A2");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SolicitudesAPI.Models.AcuerdoSeguimiento", b =>
                {
                    b.HasOne("SolicitudesAPI.Models.Denuncia", "Denuncia")
                        .WithMany("Acuerdos")
                        .HasForeignKey("DenunciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Denuncia");
                });

            modelBuilder.Entity("SolicitudesAPI.Models.ExpedienteDigital", b =>
                {
                    b.HasOne("SolicitudesAPI.Models.Denuncia", "Denuncia")
                        .WithMany("Documentos")
                        .HasForeignKey("DenunciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Denuncia");
                });

            modelBuilder.Entity("SolicitudesAPI.Models.Denuncia", b =>
                {
                    b.Navigation("Acuerdos");

                    b.Navigation("Documentos");
                });
#pragma warning restore 612, 618
        }
    }
}
